homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform

config.schema.json

Latest available version on the App Store.

Increase app version to 1.14.0

---

package-lock.json
package.json
src/accessories/indoor-unit.ts
src/comfort-cloud.ts
src/platform.ts

Addresses feedback from #9 and #12.

Improve error handling

---

package-lock.json
package.json
src/accessories/indoor-unit.ts
src/accessories/outdoor-unit.ts

- Add serial number declaration for outdoor unit
- Add null checks for indoor unit characteristics

Accessory characteristics improvements

---

config.schema.json
src/settings.ts

Bump to latest available app version

---

package-lock.json
package.json

Left out in previous pull request, which bars the npm publish flow.

Bump plugin version

---

README.md
package-lock.json
package.json
src/accessories/indoor-unit.ts
src/enums.ts
src/types.ts

Add support for quiet and powerful modes

---

.eslintrc
README.md
config.schema.json
package-lock.json
package.json
src/accessories/indoor-unit.ts
src/comfort-cloud.ts
src/enums.ts
src/platform.ts
src/types.ts

Adds support for both swing modes, controlled by the 'Oscillate' toggle in the Home app.
Resolves #27 and #50.

Improve swing mode

---

package-lock.json
package.json
src/platform.ts
src/settings.ts

Switching from static to increasing time intervals.

Adjust login retry strategy

---

config.schema.json
package.json
src/platform.ts

- without limit of login attempts
- checking for new app strore version on 1, 5, 10, 15 etc. attempt

Handle login

---

config.schema.json
src/platform.ts

- corrected log description.
- fixed time
- Improved description for Debug in config.schema

patch to handle login errors

---

src/accessories/indoor-unit.ts

fix for indoor unit

---

config.schema.json
package.json
src/accessories/indoor-unit.ts
src/types.ts

- choose the default value when starting the AC for: swing, eco navi and inside cleaning
- decide what to control the oscilate switch
- new config look

Start values and oscilate switch - support for Eco Navi, Inside Cleaning, Nanoe

---

src/accessories/indoor-unit.ts
src/types.ts

- more logs info
- some cleaning
- added ecoFunctionData

some last fixes before first beta

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/create-beta-release.yml
.github/workflows/create-production-release.yml
.github/workflows/tag-commit.yml

Fixes workflow issues that prevent them from running (correctly).

Fix workflows

---

config.schema.json
package-lock.json
package.json
src/accessories/indoor-unit.ts
src/comfort-cloud.ts
src/platform.ts

Cleaning up branches as discussed.
Committing this work on behalf of @mkz212, hence not signing responsible for the checklist below.

Merge 1.7.1

---

.github/workflows/create-beta-release.yml
.github/workflows/create-production-release.yml

Fix workflow typos

---

README.md
config.schema.json
package-lock.json
package.json
src/accessories/indoor-unit.ts
src/platform.ts
src/settings.ts

- add documentation
- change default refresh interval from 60 s to 10 s
- add option in config - Refresh Interval

Add documentation for new 1.8.1 features + add new option in config - update interval

---

package-lock.json
package.json
src/platform.ts

- display error code when login failed
- displays other recommendations for action depending on the error code

Display error code when failed login

---

.github/workflows/stale.yml
CONTRIBUTING.md
README.md
docs/config.md
docs/contributing-collaborators.md
docs/contributing-maintainers.md
package-lock.json
package.json

- update messages in close stale issues / pr
- update readme (advanced config in new file)
- add logo to readme

Some small fixes

---

src/platform.ts

- trim whitespaces from each element
- remove empty elements

Update platform.ts - exclude devices

---

README.md
config.schema.json
src/accessories/indoor-unit.ts

10 minutes when device is on and 60 minutes when device is off

Change refresh interval 

---

package-lock.json
package.json
src/comfort-cloud.ts

Use cookie jar to maintain session
Also deals with relative/absolute location headers.
I can now get all the way through to step 6 (getting a new token by `POST`ing to `https://accsmart.panasonic.com/auth/v2/login`) where I'm blocked by CloudFront:
```html
<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n <HTML>
<HEAD>
<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n<TITLE>ERROR: The request could not be
satisfied</TITLE>\n</HEAD>
<BODY>\n<H1>403 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n
<HR noshade size=\"1px\">\nRequest blocked.\nWe can't connect to the server for this app or website at this time.
There might be too much traffic or a configuration error. Try again later, or contact …
```

Use Cookie Jar

---

src/comfort-cloud.ts

This should allow us to complete the login flow

Login fix 2

---

src/comfort-cloud.ts

You need to prepend `Bearer ` to the token

Fix access tokens

---

.gitignore
docs/contributing-collaborators.md
package.json
src/comfort-cloud.ts
test/test-discover.ts
test/test-login.ts

As discussed in #330 I have added some files and a short description to the collaboration md file for you.
Have a look whether you think this will be valuable or not, and let me know.

Add instructions for an easier way of testing the plugin

---

package.json

- https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2
- https://github.com/npm/node-semver#versions

Prepare for homebridge v2

---

src/comfort-cloud.ts

This is untested. Work in progress.
I am limited on time - if someone is able to test this and post results, that would be amazing. Thanks!
Potentially fixes:
- https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/issues/525

Add cfc api key generation function

---

README.md
config.schema.json
src/indoor-unit.ts

Two options have been added to the configuration, refresh interval, separately for the device turned on and separately for the turned off, also with the possibility of turning refresh off.

Add to config options to select refresh interval

---

src/comfort-cloud.ts

Reverts homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#641

Revert "Update comfort-cloud.ts"

---

src/indoor-unit.ts

Reverts homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#640

Revert "Update indoor-unit.ts"

---

package-lock.json

Reverts homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#665

Revert "Bump cheerio from 1.0.0 to 1.1.0"
